version: '3.8'

x-versions: &versions
  POSTGRES_VERSION: 15
  ZIPKIN_VERSION: 2.23.16

x-env-vars: &env-vars
  PG_DB: graphql-kotlin-demoapp
  PG_USERNAME: graphql-kotlin-demoapp
  PG_PASSWORD: graphql-kotlin-demoapp

services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - '5432:5432'

  zipkin:
    image: "openzipkin/zipkin:${ZIPKIN_VERSION}"
    ports:
      - '9411:9411'

  graphql-kotlin-demoapp:
    image: graphql-kotlin-demoapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${PG_DB}
      SPRING_DATASOURCE_USERNAME: ${PG_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
      ZIPKIN_BASE_URL: http://zipkin:9411